# ----------- References -----------------
# https://refactoring.ninja/posts/2021-07-15-publishing-a-unity-webgl-game-from-scratch-in-under-30-minutes/#activate-unity-license-for-your-repository
# ----------------------------------------

# This is a basic workflow to help you get started with Actions

name: Linux License Request

# manually 
# https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
# on: [ workflow_dispatch ]
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
on:
  push:
    paths:
      - unity-version.txt

env:
  VERSIONING_FILE_PATH: "unity-version.txt"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # https://unity-ci.com/docs/github/activation
  activation:
    name: Request manual activation file 🔑
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Get Unity version from file
      - name: Read file contents
        id: read_file
        uses: andstor/file-reader-action@v1
        with:
          path: ${{ env.VERSIONING_FILE_PATH }}
      
      - name: Version from file
        run: echo ${{steps.read_file.outputs.contents}}

      - name: Setting Unity version env variable
        run: echo "UNITY_VERSION=${{steps.read_file.outputs.contents}}" >> $GITHUB_ENV

      - name: Version from env.variable
        run: echo "${{ env.UNITY_VERSION }}"


      - name: Unity - Request Activation File
        uses: game-ci/unity-request-activation-file@v2.0-alpha-1
        id: getManualLicenseFile
        with:
          unityVersion: ${{ env.UNITY_VERSION }}
          # Custom parameters to configure the build.
          # Parameters must start with a hyphen (-) and may be followed by a value (without hyphen). Parameters without a value will be considered booleans (with a value of true).
          # customParameters: '-nographics' # <--- This is the important bit [https://github.com/webbertakken/unity-builder/issues/153]

      # Upload artifact (Unity_v20XX.X.XXXX.alf)
      - name: Expose as artifact
        uses: actions/upload-artifact@v1
        with:
          name: Unity_${{ env.UNITY_VERSION }}_activation_file
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}