# ----------- References -----------------
# https://refactoring.ninja/posts/2021-07-15-publishing-a-unity-webgl-game-from-scratch-in-under-30-minutes/#activate-unity-license-for-your-repository
# ----------------------------------------

# This is a basic workflow to help you get started with Actions

name: Linux License Request

# manually 
# https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
# on: [ workflow_dispatch ]
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
on:
  push:
    exlude_paths:
      - unity-version.txt

env:
  VERSIONING_FILE_PATH: "unity-version.txt"
  BUTLER_API_KEY: ${{ secrets.BUTLER_CREDENTIALS }}
  BUILD_OUTPUT_PATH: build
  ITCHIO_GAME: itch-github-ci
  ITCHIO_USER: L4ZZA
  BUILD_NAME: Itchio-Github-Unity-CI
  RELEASE_NAME: Itchio-Github-Unity-CI
  BUTLER_PATH: ./butler_folder

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Web Build and deployment
    runs-on: ubuntu-latest
    strategy:
      # fail-fast: false
      matrix:
        targetPlatform:
          - WebGL
          # - StandaloneLinux64
          #- StandaloneWindows64
          #- StandaloneWindows
          #- StandaloneOSX
        butlerChannel:
          - html5

  # https://unity-ci.com/docs/github/activation
  activation:
    name: Web Build and deployment
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Get Unity version from file
      - name: Read file contents
        id: read_file
        uses: andstor/file-reader-action@v1
        with:
          path: ${{ env.VERSIONING_FILE_PATH }}
      
      - name: Version from file
        run: echo ${{ steps.read_file.outputs.contents }}

      - name: Setting Unity version env variable
        run: echo "UNITY_VERSION=${{ steps.read_file.outputs.contents }}" >> $GITHUB_ENV

      - name: Version from  env.variable
        run: echo "${{ env.UNITY_VERSION }}"

      - Building game
        uses: game-ci/unity-builder@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          # Version of unity to use for building the project.
          unityVersion: ${{ env.UNITY_VERSION }}
          # Path where the builds should be stored.
          buildsPath: ${{ env.BUILD_OUTPUT_PATH }}
          buildName: ${{ env.BUILD_NAME }}
          # Platform that the build should target.
          targetPlatform: ${{ matrix.targetPlatform }}

      - name: Directory content after build
        run: ls -al

      - name: Tree structure
        run: |
          sudo apt-get install tree
          tree ${{ env.BUILD_OUTPUT_PATH }}

      # Output
      - name: Archive
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.RELEASE_NAME }}-${{ matrix.targetPlatform }}-${{ env.UNITY_VERSION }}
          path: ${{ env.BUILD_OUTPUT_PATH }}/${{ matrix.targetPlatform }}

      - name: Butler Push
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ env.BUTLER_API_KEY }}
          CHANNEL: ${{ matrix.butlerChannel }}
          ITCH_GAME: ${{ env.ITCHIO_GAME }}
          ITCH_USER: ${{ env.ITCHIO_USER }}
          PACKAGE: build/${{ matrix.targetPlatform }}


      # TODO - Create release https://github.com/marketplace/actions/upload-a-release-asset